## NumPy Introduction
### What is NumPy?
- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
- NumPy stands for Numerical Python.
### Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

In [2]:
#Installation of NumPy
#pip install numpy

### Checking NumPy Version
The version string is stored under __version__ attribute.

In [4]:
import numpy

print(numpy.__version__)

1.26.4


Now NumPy is imported and ready to use.

In [6]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [7]:
# NumPy is usually imported under the np alias.
import numpy as np

In [8]:
ar = np.array([1, 2, 3, 4, 5])

print(ar)

print(type(ar))

[1 2 3 4 5]
<class 'numpy.ndarray'>


We can create a NumPy ndarray object by using the array() function.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [11]:
# Use a tuple to create a NumPy array
arr1 = np.array((1, 2, 3, 4, 5))

print(arr1)

[1 2 3 4 5]


In [12]:
# Create a 0-D array with value 42
arr2 = np.array(42)

print(arr2)

42


In [13]:
# Create a 2-D array containing two arrays
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr3)

[[1 2 3]
 [4 5 6]]


In [14]:
# Create a 3-D array with two 2-D arrays
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr4)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
# Check Number of Dimensions
print(arr2.ndim)
print(arr.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [16]:
# Higher Dimensional Arrays
a = np.array([1, 2, 3, 4], ndmin=7)

print(a)
print('number of dimensions :', a.ndim)

[[[[[[[1 2 3 4]]]]]]]
number of dimensions : 7


### Access Array Elements
Array indexing is the same as accessing an array element.
You can access an array element by referring to its index number.
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [18]:
b = np.array([1, 2, 'man', 4])

print(b[1])

print(b[2] + b[3])

2
man4


In [19]:
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', c[0, 1])

print('5th element on 2nd row: ', c[1, 4])

print('Last element from 2nd dim: ', c[1, -1])

2nd element on 1st row:  2
5th element on 2nd row:  10
Last element from 2nd dim:  10


In [20]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(d[0, 1, 2])

6


### NumPy Array Slicing
- Slicing in python means taking elements from one given index to another given index.

- We pass slice instead of index like this: [start:end].

- We can also define the step, like this: [start:end:step].

- If we don't pass start its considered 0

- If we don't pass end its considered length of array in that dimension

- If we don't pass step its considered 1

In [22]:
e = np.array([1, 2, 3, 4, 5, 6, 7])

print(e[1:5])

[2 3 4 5]


In [23]:
print(e[4:])

[5 6 7]


In [24]:
print(e[:4])

[1 2 3 4]


In [25]:
print(e[-5:-2])

[3 4 5]


In [26]:
print(e[1:5:2])

[2 4]


In [27]:
print(e[::2])

[1 3 5 7]


In [28]:
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(c[1, 1:4])

[7 8 9]


In [37]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 2)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,2)

In [43]:
# Unknown Dimension
# Convert 1D array with 8 elements to 3D array with 2x2 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
# Flattening the arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
